"""Record how every approved rubric line classifies, so drift is visible.

`classify` runs every intent's patterns against every line. Nothing scopes an
intent to the source that introduced it, so adding one re-classifies the whole
corpus, and *tightening* one can silently stop matching lines in a source
nobody was looking at. Both have happened:

* `manual-traction` reached "anatomic position" in source 5, which is the
  anatomical reference posture and not a traction step.
* `splint` reached "Check all interventions (oxygen, bleeding control,
  collar/splints)" in source 16 — a line that *mentions* splints rather than
  applying one.
* narrowing `manual stabiliz` for source 33 dropped
  `spinal-motion-restriction` off a source 15 line that says "Keep manual
  stabilization until the patient is fully secured".

None of it failed a test. The hint guard asks only whether *some* line produces
an intent, which stays true while individual lines come and go.

This snapshot is the missing diff. It is checked in, and
`tests/test_intent_snapshot.py` fails when it goes stale, printing what changed.
Regenerate it deliberately, and read the diff before committing it — a change
here is a change to how every future call is graded:

    python -m ems.cli.intent_snapshot --update
    python -m ems.cli.intent_snapshot            # print, don't write
"""

import argparse
import re
from pathlib import Path

from ems.frontmatter import read_page
from ems.scenarios import list_approved
from ems.sim.grade import parse_actions
from ems.sim.intents import classify

SNAPSHOT = Path(__file__).resolve().parents[2] / "tests" / "data" / "intent_snapshot.txt"

_HEADER = """\
# Generated by `python -m ems.cli.intent_snapshot --update`. Do not hand-edit.
#
# <scenario>:<step>  <intents, or "-">  | <the line, truncated>
#
# A diff here is a change in how the grader reads the corpus. Review it the way
# you would review the grading change itself.
"""


def _excerpt(line: str, width: int = 72) -> str:
    """The line, on one row, with citations stripped so page edits do not churn."""
    plain = " ".join(re.sub(r"\[SRC-[^\]]*\]", "", line).split())
    return plain if len(plain) <= width else plain[: width - 1] + "…"


def render() -> str:
    """The snapshot for the corpus as it stands right now."""
    rows = [_HEADER]
    for path in sorted(list_approved()):
        for i, line in enumerate(parse_actions(read_page(path)[1]), 1):
            intents = ",".join(sorted(classify(line))) or "-"
            rows.append(f"{path.stem}:{i:02d}  {intents}  | {_excerpt(line)}")
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="protocol-intent-snapshot",
        description="Record how every approved rubric line classifies.",
    )
    parser.add_argument("--update", action="store_true",
                        help="Rewrite the checked-in snapshot")
    args = parser.parse_args()

    current = render()
    if args.update:
        SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        changed = not SNAPSHOT.exists() or SNAPSHOT.read_text() != current
        SNAPSHOT.write_text(current)
        print(f"{'updated' if changed else 'unchanged'}: {SNAPSHOT}")
    else:
        print(current, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
